/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-15 12:43:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.company;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class companyView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>난 혼자산다 관리자 : (회사명)</title>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Sunflower:300,500,700&display=swap&subset=korean\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tbackground-color: #dcdcdc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 메뉴와 작성할 구간 스타일*/\r\n");
      out.write("#bodybase {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 작성할 구간*/\r\n");
      out.write("#centerbody {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\twidth: 85%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("/* 메뉴바 첫 div */\r\n");
      out.write("#accordian {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tbackground: #333333;\r\n");
      out.write("\twidth: 250px;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tbox-shadow: 0 5px 15px 1px rgba(0, 0, 0, 0.6), 0 0 200px 1px\r\n");
      out.write("\t\trgba(255, 255, 255, 0.5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 메뉴 스타일 */\r\n");
      out.write("#accordian h3 {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tline-height: 34px;\r\n");
      out.write("\tpadding: 0 1px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tbackground: #064461;\r\n");
      out.write("\tbackground: linear-gradient(#003040, #002535);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* h3카테고리 스타일*/\r\n");
      out.write("#accordian h3:hover {\r\n");
      out.write("\ttext-shadow: 0 0 1px rgba(255, 255, 255, 0.7);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 아이콘폰트 스타일 */\r\n");
      out.write("#accordian h3 span {\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\tmargin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#accordian li {\r\n");
      out.write("\tlist-style-type: none;\r\n");
      out.write("}\r\n");
      out.write("/* 서브메뉴 스타일 */\r\n");
      out.write("#accordian ul ul li a {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tfont-size: 11px;\r\n");
      out.write("\tline-height: 27px;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tpadding: 0 15px;\r\n");
      out.write("\t-webkit-transition: all 0.15s;\r\n");
      out.write("\t-moz-transition: all 0.15s;\r\n");
      out.write("\t-o-transition: all 0.15s;\r\n");
      out.write("\t-ms-transition: all 0.15s;\r\n");
      out.write("\ttransition: all 0.15s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#accordian ul ul li a:hover {\r\n");
      out.write("\tbackground: #003545;\r\n");
      out.write("\tborder-left: 5px solid #09c;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* active 클래스 외에 것은 보이지 않게 하기 */\r\n");
      out.write("/* #accordian ul ul {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#accordian li.active ul {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}  */\r\n");
      out.write("#underbar {\r\n");
      out.write("\theight: 4px;\r\n");
      out.write("\tbackground-color: black;\r\n");
      out.write("\tbox-shadow: 10px 10px -10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#homemenu hr {\r\n");
      out.write("\theight: 4px;\r\n");
      out.write("\tbackground-color: black;\r\n");
      out.write("\tbox-shadow: 10px 10px -10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#homemenu {\r\n");
      out.write("\tmargin-top: 20px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".CompanyInfo1 {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tmargin-right: 100px;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\tline-height: 30px;\r\n");
      out.write("\tfont-family: Sunflower;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".CompanyInfo1 button {\r\n");
      out.write("\tmargin-right: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* main페이지 이미지 */\r\n");
      out.write("#homeimg , #homeimg{\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\t/* \tborder: 1px solid black; */\r\n");
      out.write("\tmargin-left: 50px;\r\n");
      out.write("\tmargin-top: 50px;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* user 텍스트 스타일*/\r\n");
      out.write("#hometext , #hometext:hover{\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tfont-family: Sunflower;\r\n");
      out.write("\tmargin-left: 20px;\r\n");
      out.write("\tmargin-top: 50px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#hometext h4 {\r\n");
      out.write("\tmargin-top: 50px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#rogout {\r\n");
      out.write("\tbackground-color: #555555;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tborder: 2px solid #555555;\r\n");
      out.write("\tmargin-left: 55px;\r\n");
      out.write("\twidth: 150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#rogout:hover {\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"homemenu\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div id=\"homeimg\" onclick = \"C_home();\">\r\n");
      out.write("\t\t\t");
      out.write("\t\t\t\t<img id=\"homeicon\"\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/images/home.png\" width=\"80px\"\r\n");
      out.write("\t\t\t\t\theight=\"80px\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"hometext\" onclick = \"C_home();\">\r\n");
      out.write("\t\t\t\t<h1>난 혼자 산다</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"hometext\" onclick = \"C_home();\">\r\n");
      out.write("\t\t\t\t<h4>(관리자)</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t<!-- \t</a> -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"CompanyInfo1\">\r\n");
      out.write("\t\t<fieldset id = \"roginuser\">\r\n");
      out.write("\t\t<legend align=\"center\">로그인</legend>\r\n");
      out.write("\t\t\t<label>회사명 : </label><input type= \"text\" value=\"나혼자산다\" readonly=\"readonly\" disabled><br>\r\n");
      out.write("\t\t\t<label>담당자 : </label><input type= \"text\" value=\"나혼자산다\" readonly=\"readonly\" disabled><br> \r\n");
      out.write("\t\t\t<label>연락처 : </label><input type= \"text\" value=\"나혼자산다\" readonly=\"readonly\" disabled><br>\r\n");
      out.write("\t\t\t<button id=\"rogout\" >로그아웃</button>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br clear=\"both\">\r\n");
      out.write("\t<hr id=\"underbar\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"bodybase\">\r\n");
      out.write("\t\t<div id=\"accordian\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-category\"></span>상품카테고리\r\n");
      out.write("\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">상품등록</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">상품수정</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">상품삭제</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">상품재고</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"active\">\r\n");
      out.write("\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-money\"></span>매출확인\r\n");
      out.write("\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">매출판매량</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">기간별 매출량</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-qna\"></span>QnA\r\n");
      out.write("\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">1:1 QnA 확인</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">공지사항 등록</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">블랙컨슈머</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-info\"></span>정보수정\r\n");
      out.write("\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">정보수정</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">탈퇴</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id = \"centerbody\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction C_home(){\r\n");
      out.write("\t\t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/views/company/companyView.jsp\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
